# Netlify configuration for Next.js
# https://docs.netlify.com/integrations/frameworks/next-js/

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
